name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  canonical-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.2"
      - run: terraform -chdir=modules/canonical_tags init -backend=false
      - run: terraform -chdir=modules/canonical_tags test
